# Generated by Django 4.2 on 2026-02-13 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('HONEYMOON', 'Honeymoon'), ('FAMILY', 'Family'), ('ADVENTURE', 'Adventure'), ('PILGRIMAGE', 'Pilgrimage'), ('CUSTOM', 'Custom')], max_length=20)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField(blank=True, help_text='Admin will set the travel date. Format: YYYY-MM-DD', null=True)),
                ('scheduled_time', models.TimeField(blank=True, help_text='Admin will set the travel time. Format: HH:MM (24-hour)', null=True)),
                ('pickup_location', models.CharField(max_length=200)),
                ('drop_location', models.CharField(max_length=200)),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_days', models.IntegerField(default=1)),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'Sedan (4-Seater)'), ('ERTIGA', 'ERTIGA (6-7 Seater)'), ('TEMPO', 'Tempo Traveler (12 Seater)'), ('BUS', 'Mini Bus (20-25 Seater)')], max_length=20)),
                ('max_passengers', models.IntegerField(default=4)),
                ('base_price', models.IntegerField()),
                ('advance_amount', models.IntegerField(default=1000)),
                ('is_festival_rate', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('inclusions', models.TextField(help_text='Separate with comma')),
                ('exclusions', models.TextField(help_text='Separate with comma')),
                ('important_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_km', models.IntegerField(default=14)),
                ('festival_price', models.IntegerField(default=16)),
            ],
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('passengers_count', models.IntegerField(default=1)),
                ('special_requirements', models.TextField(blank=True)),
                ('total_amount', models.IntegerField()),
                ('advance_paid', models.IntegerField(default=1000)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('ADVANCE_PAID', 'Advance Paid'), ('FULLY_PAID', 'Fully Paid')], default='PENDING', max_length=20)),
                ('invoice_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='packages.package')),
            ],
            options={
                'verbose_name': 'Package Booking',
                'verbose_name_plural': 'Package Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
