# Generated by Django 4.2 on 2026-02-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_packagebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='vehicle_type',
            field=models.CharField(choices=[('SEDAN', 'Sedan (4-Seater)'), ('ERTIGA', 'ERTIGA (6-7 Seater)'), ('TEMPO', 'Tempo Traveler (12 Seater)'), ('BUS', 'Mini Bus (20-25 Seater)')], max_length=20),
        ),
    ]
