# Generated by Django 4.2 on 2026-02-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagebooking',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='packagebooking',
            name='travel_time',
        ),
        migrations.AddField(
            model_name='package',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Admin will set the travel date', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Admin will set the travel time', null=True),
        ),
    ]
