# Generated by Django 4.2 on 2026-02-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_packagebooking_travel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Admin will set the travel date. Format: YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Admin will set the travel time. Format: HH:MM (24-hour)', null=True),
        ),
    ]
